name: release

on:
  release:
    types: [published]

permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: pip install poetry
    - run: poetry --version
    - run: poetry install
    - run: bash run.sh test
    - run: bash run.sh lint
    - run: poetry build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
